module.exports = {
  plugins: ['npm', 'conventional-commits'],
  onlyPublishWithReleaseLabel: true,
  labels: [
    {
      name: 'release:major',
      changelogTitle: '💥 Breaking Change',
      description: 'Increment the major version when merged',
      releaseType: 'major',
      color: '#C5000B',
      overwrite: true,
    },
    {
      name: 'release:minor',
      changelogTitle: '🚀 Enhancement',
      description: 'Increment the minor version when merged',
      releaseType: 'minor',
      color: '#F1A60E',
      overwrite: true,
    },
    {
      name: 'release:patch',
      changelogTitle: '🐛 Bug Fix',
      description: 'Increment the patch version when merged',
      releaseType: 'patch',
      color: '#392EC0',
      overwrite: true,
    },
    {
      name: 'release:skip',
      description: 'Preserve the current version when merged',
      releaseType: 'skip',
      color: '#64748b',
      overwrite: true,
    },
    {
      name: 'release:internal',
      changelogTitle: '🏠 Internal',
      description: 'Changes only affect the internal API',
      releaseType: 'none',
      color: '#fcd34d',
      overwrite: true,
    },
    {
      name: 'release:docs',
      changelogTitle: '📝 Documentation',
      description: 'Changes only affect the documentation',
      releaseType: 'none',
      color: '#57534e',
      overwrite: true,
    },
    {
      name: 'release:tests',
      changelogTitle: '🧪 Tests',
      description: 'Add or improve existing tests',
      releaseType: 'none',
      color: '#67e8f9',
      overwrite: true,
    },
    {
      name: 'release:perf',
      changelogTitle: '🏎 Performance',
      description: 'Improve performance of an existing feature',
      releaseType: 'patch',
      color: '#84cc16',
      overwrite: true,
    },
  ],
};
